version: '3.9'

services:
  bot:
    build: .
    container_name: task_tracker_bot
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    command: python main.py
